@echo off
echo Starting ReelEyes (Simple Version)...
cd backend
echo Installing minimal dependencies...
python -m pip install Flask Flask-CORS requests
echo Starting server...
python simple_app.py
pause